// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECvGv_izkCZNuvb06Tpwz3uyydUGDtXE',
    appId: '1:649388758016:android:a0316be36a23dc1d0374e5',
    messagingSenderId: '649388758016',
    projectId: 'ifcm-tunes-global',
    storageBucket: 'ifcm-tunes-global.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR41vVOyRV2nlVog6jMhdxeARSQ89wYxM',
    appId: '1:649388758016:ios:053b39b01a84c3db0374e5',
    messagingSenderId: '649388758016',
    projectId: 'ifcm-tunes-global',
    storageBucket: 'ifcm-tunes-global.firebasestorage.app',
    iosBundleId: 'com.example.ifcmTunes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdLAara7DFv6apQRoqPSnrdij8hDZOABI',
    appId: '1:649388758016:web:9b26b119277960780374e5',
    messagingSenderId: '649388758016',
    projectId: 'ifcm-tunes-global',
    authDomain: 'ifcm-tunes-global.firebaseapp.com',
    storageBucket: 'ifcm-tunes-global.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR41vVOyRV2nlVog6jMhdxeARSQ89wYxM',
    appId: '1:649388758016:ios:053b39b01a84c3db0374e5',
    messagingSenderId: '649388758016',
    projectId: 'ifcm-tunes-global',
    storageBucket: 'ifcm-tunes-global.firebasestorage.app',
    iosBundleId: 'com.example.ifcmTunes',
  );

}